server:
  #?????
  port: 8081 #?????8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/renmuqingzi?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    url: jdbc:mysql://localhost:3306/renmuqingzi
    user: root
    password: root
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# ??mybatis
mybatis:
  #??pojo??????mybatis?????????pojo??
  type-aliases-package: com.example.renmuqingzi.pojo
  #??????Mapper?????XML?? classpath:xml????
  mapper-locations: classpath:mapper/*.mysql.xml
